<?xml version="1.0"?>
<!DOCTYPE document [
<!ELEMENT document (properties,body)>
<!ELEMENT properties (title,author)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author
      email CDATA #IMPLIED
>

<!ELEMENT body (release+)>
<!ELEMENT release (action+)>
<!ATTLIST release
      version CDATA #REQUIRED
      date CDATA #IMPLIED
      description CDATA #IMPLIED
>
<!ELEMENT action (#PCDATA)>
<!ATTLIST action
      type (add|remove|update|fix) #REQUIRED
      dev CDATA #REQUIRED
>
]>
<document>
    <properties>
        <title>Changes</title>
        <author email="j.kapitza(at)schwarze-allianz.de">Jens Kapitza</author>
    </properties>
    <body>
        <release version="1.6.0" date="In Version-Control-System" description="">
            <action type="fix" dev="jenskapitza">Update ...</action>
        </release>
        <release version="1.5.8" date="In Version-Control-System" description="">
            <action type="update" dev="victor-homyakov">TODO</action>
        </release>
        <release version="1.5.7" date="29.03.2012" description="">
            <action type="update" dev="victor-homyakov">Merged attributes 'source' and 'action'
               on updateField tag.</action>
        </release>
        <release version="1.5.6" date="25.07.2011" description="">
        </release>
        <release version="1.5.2" date="01.09.2010" description="">
            <action type="update" dev="jenskapitza">Move VersionControl back to sf.net</action>
            <action type="update" dev="jenskapitza">fix and change some pom stuff (e.g. namespace)</action>
            <action type="remove" dev="jenskapitza">StringUtilTest</action>
        </release>
        <release version="1.5.1" date="30.11.2009" description="">
            <action type="add" dev="victor-homyakov">JavaScript Unit tests.</action>
            <action type="add" dev="victor-homyakov">More JUnit tests.</action>
            <action type="update" dev="victor-homyakov">Added attributes 'preFunction', 'postFunction',
               'errorFunction' to form submit tag.</action>
        </release>
        <release version="1.5" date="15.09.2009" description="">
            <action type="update" dev="jenskapitza">Change the GroupID and update the pom.xml file.</action>
            <action type="add" dev="jenskapitza">XMLUtils methods updated</action>
            <action type="fix" dev="jenskapitza">XML-Ident problem</action>
            <action type="fix" dev="victor-homyakov">Fixed bug with anchor titles in AjaxToggleTag.</action>
            <action type="update" dev="victor-homyakov">New form submit tag.</action>
            <action type="update" dev="victor-homyakov">Added 'var' and 'attachTo' attributes to tree tag.</action>
            <action type="fix" dev="jenskapitza">Update Documentation</action>
            <action type="fix" dev="victor-homyakov">Autocompleter popup div is inserted at the top of the DOM
                hierarchy to prevent overflow.</action>
            <action type="fix" dev="victor-homyakov">Added default attribute values to AjaxDisplayTag.
                AjaxDisplayTag with empty attributes will not rewrite links.</action>
            <action type="fix" dev="victor-homyakov">Fixed AjaxAreaTag.</action>
            <action type="fix" dev="victor-homyakov">Fixed AjaxJspTag.Toggle.</action>
            <action type="fix" dev="victor-homyakov">Fixed AjaxJspTag.Base#buildParameterString for checkbox
                and select-multiple input fields.</action>
            <action type="fix" dev="jenskapitza">TLD now validate</action>
            <action type="remove" dev="jenskapitza">Remove Reflection usage and refactor to interface
            </action>
            <action type="update" dev="jenskapitza">Changed Website, and documentation</action>
            <action type="fix" dev="jenskapitza">Portlet autorefresh never stops. Now we do break execution
                if source is not in DOM tree</action>
            <action type="remove" dev="jenskapitza">Portlet attribute withBar removed.</action>
            <action type="update" dev="jenskapitza">Depends on JSP-API 2.1 and Servlet-API 2.5, cause flush
                does not work with area styled tags.</action>
            <action type="update" dev="jenskapitza">we moved to Mercurial.</action>
            <action type="add" dev="jenskapitza">import version 1.3.</action>
            <action type="remove" dev="jenskapitza">drop support for java 1.4 and later</action>
            <action type="remove" dev="jenskapitza">drop jericho html. and use integrated xml parser. this
                force the user to write xhtml</action>
        </release>
        <release version="1.4" date="BLACKLISTED" description="">
            <action type="add" dev="jenskapitza">this version is blacklisted this version was used for
                testing javascript functions. this version was not compatible.</action>
        </release>
        <release version="1.3" date="out of date" description="this was the starting base">
            <action type="add" dev="jenskapitza">The old upstream version. No longer Supported.</action>
        </release>
    </body>
</document>
